Feature/parsing vacancies data
StGrail/v_it pull request #4
Opened 2020-12-30 08:16 UTC by alexeyt101

1. Create table of postgres database;
2. Create parser of hh_ru vacancies and their saving in the database;
3. Create parser of vacancy skills to true/false and data saving in database.

2021-01-16 08:35 UTC, technogleb requested changes

2021-01-16 08:35 UTC, technogleb commented on .gitignore
> -# Byte-compiled / optimized / DLL files
Почему у тебя так отличается .gitignore? Лучше возьми версию из мастера, она более полная.

2021-01-16 08:35 UTC, technogleb commented on parser_vacancies_data/checking_vacancy_for_skills.py
> +    for skill in skill_list:
В данной функции тебе нужно получить лишь первый скилл? Или все скилы из skill_list, которые есть в PROCESSING_SKILLS? Если второе, то оно так не сработает, а вернет лишь первый и закончит работу.

2021-01-16 08:35 UTC, technogleb commented on parser_vacancies_data/checking_vacancy_for_skills.py
> +        if skill in config.PROCESSING_SKILLS:
если ты здесь в любом случае проверяешь наличие скила в config.PROCESSING_SKILLS, зачем ты дополнительно делаешь это в 7 строчке?

2021-01-16 08:35 UTC, technogleb commented on parser_vacancies_data/config.py
> +min_lenght_skill_letter = 0
Судя по логике кода, это минимально требуемая длина скилла, то есть максимальная длина из всех PROCESSING_SKILLS?
Как вариант, такой кусок кода можно написать вот так 
```
sorted(lst, key=lambda x: len(x))[-1]
```

2021-01-16 08:35 UTC, technogleb commented on parser_vacancies_data/create_db.py
> +import config_db
здесь висе ок, в принципе

2021-01-16 08:35 UTC, technogleb commented on parser_vacancies_data/create_saving_sql_query.py
> +    return skills_str[:-1]
```suggestion
def change_format_skills(skills):
    '''
    Принимает на входе словарь, содержащий скиллы вакансии.
    Возвращает строку скиллов, необходимую для SQL команды на запись в БД
    '''
    return ','.join([skill for _, skill in skills.items()])
```

2021-01-16 08:35 UTC, technogleb commented on parser_vacancies_data/create_saving_sql_query.py
> +    return skills_str[:-1]
Кстати итерироваться сразу по ключам и значениям нужно вот так
```
for key, value in some_dict.items():
        blah, blah, blah
```

2021-01-16 08:35 UTC, technogleb commented on parser_vacancies_data/create_saving_sql_query.py
> +    vacancy_data['experience'] = vacancy['experience']['name'].lower()
стоит объединить эти строчки в одну

2021-01-21 13:44 UTC, alexeyt101 commented on .gitignore
> -# Byte-compiled / optimized / DLL files
Да, взял её, конечно.

2021-01-21 13:51 UTC, alexeyt101 commented on parser_vacancies_data/checking_vacancy_for_skills.py
> +    for skill in skill_list:
Мне нужно получить лишь строку, которая есть в config.PROCESSING_SKILLS. Это делается для того, чтобы обработать названия скиллов, состоящих из двух слов, скажем 'atlassian jira' или 'django framework'.

2021-01-21 14:12 UTC, alexeyt101 commented on parser_vacancies_data/checking_vacancy_for_skills.py
> +        if skill in config.PROCESSING_SKILLS:
Корявенько написано, но смысл в том, что проверка в строке 7 нужна, чтобы из названия скилла, если оно больше чем одно слово, выцепить только одно слово (см. предыдущий комментарий). Проверка в 25 строчке нужна чтобы проверить скиллы, состоящие из одного слова и + skills в 22 строчке может оказаться None

2021-01-21 14:12 UTC, alexeyt101 commented on parser_vacancies_data/create_saving_sql_query.py
> +    return skills_str[:-1]
Понял, спасибо!

2021-01-30 09:45 UTC, closed without merging